In [1]:
from src.data.dataset import RankineData

data = RankineData(1)

In [2]:
data.xx

array([[ 0.,  1.,  2., ..., 88., 89., 90.],
       [ 0.,  1.,  2., ..., 88., 89., 90.],
       [ 0.,  1.,  2., ..., 88., 89., 90.],
       ...,
       [ 0.,  1.,  2., ..., 88., 89., 90.],
       [ 0.,  1.,  2., ..., 88., 89., 90.],
       [ 0.,  1.,  2., ..., 88., 89., 90.]])

In [3]:
data.yy

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 2.,  2.,  2., ...,  2.,  2.,  2.],
       ...,
       [88., 88., 88., ..., 88., 88., 88.],
       [89., 89., 89., ..., 89., 89., 89.],
       [90., 90., 90., ..., 90., 90., 90.]])

In [5]:
obs_points = data.obs_points

In [10]:
import numpy as np
# First, sort by the second dimension
sorted_indices = np.lexsort((obs_points[:, 0], obs_points[:, 1]))

# Use the sorted indices to sort the array
sorted_obs_points = obs_points[sorted_indices]

print("\nSorted obs_points:\n", sorted_obs_points)


Sorted obs_points:
 [[ 3  0]
 [16  0]
 [37  0]
 [66  0]
 [73  0]
 [18  1]
 [87  1]
 [ 6  2]
 [55  2]
 [16  5]
 [49  5]
 [15  6]
 [19  7]
 [30  7]
 [31  7]
 [36  7]
 [67  7]
 [69  7]
 [ 3  8]
 [72  8]
 [40  9]
 [44  9]
 [51 10]
 [ 6 11]
 [21 11]
 [83 11]
 [89 11]
 [ 3 12]
 [29 12]
 [ 7 13]
 [35 13]
 [27 14]
 [50 15]
 [ 1 17]
 [ 8 17]
 [20 17]
 [30 17]
 [16 18]
 [29 18]
 [81 18]
 [88 18]
 [39 19]
 [52 19]
 [60 19]
 [48 20]
 [ 2 21]
 [48 21]
 [65 21]
 [68 21]
 [56 22]
 [83 22]
 [ 1 23]
 [ 3 23]
 [45 23]
 [53 23]
 [64 23]
 [ 3 26]
 [10 26]
 [19 26]
 [36 26]
 [63 26]
 [70 26]
 [47 27]
 [53 27]
 [47 28]
 [21 29]
 [36 29]
 [37 29]
 [51 29]
 [57 30]
 [71 30]
 [32 31]
 [90 31]
 [43 33]
 [17 34]
 [63 34]
 [68 34]
 [60 35]
 [73 35]
 [20 36]
 [26 36]
 [80 36]
 [ 7 37]
 [31 38]
 [63 38]
 [46 40]
 [54 40]
 [10 42]
 [52 42]
 [77 42]
 [ 0 43]
 [15 43]
 [34 43]
 [42 43]
 [13 45]
 [19 45]
 [21 45]
 [10 47]
 [33 47]
 [59 47]
 [ 9 48]
 [11 48]
 [55 48]
 [86 48]
 [52 49]
 [41 50]
 [ 5 51]
 [22 51]
 [55 52

In [1]:
# (60,91,91)のnumpy配列を作成
import numpy as np
a = np.zeros((60, 91, 91))
a_mean = np.mean(a, axis=0)
print(a_mean.shape)

(91, 91)


In [2]:
from src.data.dataset import RankineData
ensemble_size = 60

data = RankineData(1)
x_u, x_v = data.windvalues_prior['u_x'], data.windvalues_prior['u_y']
x_u, x_v = x_u.reshape(ensemble_size, -1), x_v.reshape(ensemble_size, -1)
xb_mean_u = np.mean(x_u, axis=0)
xb_mean_v = np.mean(x_v, axis=0)
dXb_u = (x_u - xb_mean_u).T
dXb_v = (x_v - xb_mean_v).T

In [3]:
print(x_u.shape)
print(xb_mean_u.shape)
print(dXb_u.shape)

(60, 91, 91)
(91, 91)
(91, 91, 60)
